language: python

python:
- "3.6"

env:
  global:
    - BUILD_ON_TRAVIS=true

before_install:
  - mysql -e 'CREATE DATABASE herculean_test;'

install: pip install -r requirements.txt

script:
- python manage.py test